###########
# Environment
###########
@API_HOST = http://127.0.0.1:33221
@API_VERSION = v1
@GROUP = aa
@PARTITION = bb
@OBJECT_PATH = cc
@OBJECT_ID = 1857698545251913728
@FILE_PATH = ee
@VERSION = 3

###########
# API
###########
# multipart Upload
PUT  {{API_HOST}}/{{API_VERSION}}/{{GROUP}}/{{PARTITION}}/{{OBJECT_PATH}} HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundry

--MyBoundry
Content-Disposition: form-data; name="1"; filename="sample_1.mp3"
Content-Type: application/octet-stream

< ./scripts/sample/sample.mp3

--MyBoundry
Content-Disposition: form-data; name="1"; filename="sample_2.mp3"
Content-Type: application/octet-stream

< ./scripts/sample/sample.mp3

--MyBoundry
Content-Disposition: form-data; name="3"; filename="sample_3.mp3"
Content-Type: application/octet-stream

< ./scripts/sample/sample.mp3

--MyBoundry--

###

# Download last version
GET {{API_HOST}}/{{API_VERSION}}/{{GROUP}}/{{PARTITION}}/{{OBJECT_PATH}}/{{OBJECT_ID}} HTTP/1.1

###

# Download specific version
GET {{API_HOST}}/{{API_VERSION}}/{{GROUP}}/{{PARTITION}}/{{OBJECT_PATH}}/{{OBJECT_ID}}/version/{{VERSION}} HTTP/1.1

###

# Delete
DELETE {{API_HOST}}/{{API_VERSION}}/{{GROUP}}/{{PARTITION}}/{{OBJECT_PATH}}/{{OBJECT_ID}} HTTP/1.1

###

# Delete specific version
DELETE {{API_HOST}}/{{API_VERSION}}/{{GROUP}}/{{PARTITION}}/{{OBJECT_PATH}}/{{OBJECT_ID}}/version/{{VERSION}} HTTP/1.1

###

# Metadata
GET {{API_HOST}}/{{API_VERSION}}/{{GROUP}}/{{PARTITION}}/{{OBJECT_PATH}}/{{OBJECT_ID}}/metadata HTTP/1.1
Accept: application/json

###

# List
GET {{API_HOST}}/{{API_VERSION}}/{{GROUP}}/{{PARTITION}}/{{OBJECT_PATH}} HTTP/1.1
Accept: application/json

###
