sos:
  standalone: true
  explorer:
    logger:
      level: debug
      format: text
    address:
      ip: 0.0.0.0
      port: 33221
  metadata_registry:
    db:
      type: mongodb
      host: mongodb://localhost:27017
      database: sos
      log_level: debug
      credentials:
        username: root
        password: root
  block_storage:
    db:
      type: leveldb
      path: /Users/issuh/workspace/git/issuh/sos/test
