sos:
  api:
    logger:
      level: debug
      format: text
    address:
      ip: 127.0.0.1
      port: 33221
  meta:
    address:
      ip: 127.0.0.1
      port: 33222
  storage:
    address:
      ip: 127.0.0.1
      port: 33223

