sos:
  explorer:
    logger:
      level: debug
      format: text
    address:
      ip: 0.0.0.0
      port: 33221
  metadata_registry:
    address:
      host: 127.0.0.1:33222
  block_storage:
    address:
      host: 127.0.0.1:33223
